apiVersion: apps/v1
kind: Deployment
metadata:
  name: dajmir
  labels:
    app: dajmir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dajmir
  template:
    metadata:
      labels:
        app: dajmir
    spec:
      containers:
        - name: dajmir
          image: dajmir
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m