apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtv
  labels:
    app: rtv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtv
  template:
    metadata:
      labels:
        app: rtv
    spec:
      containers:
      - name: rtv
        image: rtv
        ports:
        - containerPort: 80
