apiVersion: apps/v1
kind: Deployment
metadata:
  name: stanovanjske-zadruge-deployment
  labels:
    app: stanovanjske-zadruge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stanovanjske-zadruge
  template:
    metadata:
      labels:
        app: stanovanjske-zadruge
    spec:
      containers:
      - name: stanovanjske-zadruge
        image: stanovanjske-zadruge
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
