apiVersion: apps/v1
kind: Deployment
metadata:
  name: exitect-deployment
  labels:
    app: exitect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exitect
  template:
    metadata:
      labels:
        app: exitect
    spec:
      containers:
      - name: exitect
        image: rg.fr-par.scw.cloud/djnd/exitect:latest
        ports:
        - containerPort: 80
