apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtvjezakon
  labels:
    app: rtvjezakon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtvjezakon
  template:
    metadata:
      labels:
        app: rtvjezakon
    spec:
      containers:
      - name: rtvjezakon
        image: rtvjezakon
        ports:
        - containerPort: 80
