apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stanovanjske-zadruge
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stanovanjske-zadruge.lb.djnd.si
        - peticija.zastanovanjskezadruge.si
      secretName: stanovanjske-zadruge-tls
  rules:
    - host: stanovanjske-zadruge.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stanovanjske-zadruge
                port:
                  number: 80
    - host: peticija.zastanovanjskezadruge.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stanovanjske-zadruge
                port:
                  number: 80