apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dajmir
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dajmir.djnd.si
        - dajmir.danesjenovdan.si
      secretName: dajmir-tls
  rules:
    - host: dajmir.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dajmir
                port:
                  number: 80
    - host: dajmir.danesjenovdan.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dajmir
                port:
                  number: 80