apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naravenedamo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - naravenedamo.djnd.si
        - naravenedamo.danesjenovdan.si
      secretName: naravenedamo-tls
  rules:
    - host: naravenedamo.djnd.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: naravenedamo
                port:
                  number: 80
    - host: naravenedamo.danesjenovdan.si
      http: *http_paths
