apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: breakfree
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - breakfree.djnd.si
        - breakfree.danesjenovdan.si
      secretName: breakfree-tls
  rules:
    - host: breakfree.djnd.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: breakfree
                port:
                  number: 80
    - host: breakfree.danesjenovdan.si
      http: *http_paths
