apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtvjezakon
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rtvjezakon.lb.djnd.si
      secretName: rtvjezakon-tls
  rules:
    - host: rtvjezakon.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtvjezakon
                port:
                  number: 80
