apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: naravenedamo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: naravenedamo
    newName: rg.fr-par.scw.cloud/djnd/naravenedamo
    newTag: 'b9396c70377e2c14887244528d84c570f8683057'
