apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rtv
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rtv
    newName: rg.fr-par.scw.cloud/djnd/rtv
    newTag: 'f74ee230ce3d74197cf7f925611104692d84cbb7'
