apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rtvjezakon
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rtvjezakon
    newName: rg.fr-par.scw.cloud/djnd/rtvjezakon
    newTag: '4dbb4e5530e4ebd0549c66bc217bd0e2fb929bd1'
