apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: breakfree
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: breakfree
    newName: rg.fr-par.scw.cloud/djnd/breakfree
    newTag: "latest"
