apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rtv
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rtv
    newName: rg.fr-par.scw.cloud/djnd/rtv
    newTag: '7b6fdebf2af9e1daf2bdc6c6732cdc4573d76fb3'
