apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dajmir
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: dajmir
    newName: rg.fr-par.scw.cloud/djnd/dajmir
    newTag: 'd1af2d201261977618108873c4c9f2a60c0ac642'