apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: stanovanjske-zadruge
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge
    newTag: '7ed8ed2a4abcb21b6b4d53342d3e4b73a0c9ee97'
