apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resimointernet
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: resimointernet
    newName: rg.fr-par.scw.cloud/djnd/resimointernet
    newTag: '47a9de682c9fe816765be943d8b30bd7cfd37c8b'
