
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kura
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: imasjajca
    newName: rg.fr-par.scw.cloud/djnd/imasjajca
    newTag: '78000ead79baa066998190f293a1ad28eb9e3ebb'
