apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: stanovanjske-zadruge
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge
    newTag: 'bc79b906965986ce59f0c3a3a57910cf5b69e36a'
