apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rtvjezakon
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: rtvjezakon
    newName: rg.fr-par.scw.cloud/djnd/rtvjezakon
    newTag: 'd54b33a2fa211222c9e4b99a8c7af36e7c8346bc'
