apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exitect
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: exitect
    newName: rg.fr-par.scw.cloud/djnd/exitect
    newTag: 'latest'
