apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: naravenedamo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: naravenedamo
    newName: rg.fr-par.scw.cloud/djnd/naravenedamo
    newTag: 'b8cde60b538fa8a5e2bf88b90dd00a10429fcf9f'
