apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: naravenedamo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: naravenedamo
    newName: rg.fr-par.scw.cloud/djnd/naravenedamo
    newTag: 'fb88e3ac34fca871105e4da2b2041e274b8933c5'
